[package]
name = "proc_aud"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = { version = "3", optional = true }
fastrand = { version = "2", optional = true }

[features]
wav = ["dep:hound"]
noise = ["dep:fastrand"]

[[example]]
name = "simple"
required-features = ["wav"]

[[example]]
name = "instruments"
required-features = ["wav", "noise"]

[[example]]
name = "chord_progression"
required-features = ["wav"]
